### ISSUE TITLE
CoC page for SLC doesn't work

### ISSUE THREAD

**Issue by FloorD** [devopsdays/devopsdays-web#11555]
`NET::ERR_CERT_COMMON_NAME_INVALID` for https://www.slcdevopsdays.org/code-of-conduct/ for the [2023 SLC event](https://devopsdays.org/events/2023-salt-lake-city/welcome/).

**Comment by bridgetkromhout** [comment]
This problem was discussed in https://github.com/devopsdays/devopsdays-web/pull/11276 but not resolved; the code of conduct page still linked to the broken site. As events are required to have a code of conduct, one potential fix is to link the default code of conduct (which they checked in but did not link). In https://github.com/devopsdays/devopsdays-web/pull/11643 I submit a PR which does that.

Longer-term, it is fine to link to something offsite as long as the link is functional.
