### ISSUE TITLE
Move schedule out of main data event yaml

### ISSUE THREAD

**Issue by toshywoshy** [devopsdays/devopsdays-web#13658]
If we want to have to have schedule automation, it would be better to have autogenerated files seperate from the general file.
Let say by having Pretalx output the schedule in DoD Hugo Schedule YAML format and then having a release push the YAML file to git

**Comment by mattstratton** [comment]
i think that can be an option, but I am hesitant to make a hard dependency in the website to only have this work with pretalx.

**Comment by mattstratton** [comment]
I do think that it would make sense to have a separate yaml file for the program… This is a bigger deal to implement than might appear , because it means re-factoring the entire data approach so that there is a folder for each event with multiple files instead of one folder for every event. 

I had that as part of the refactor for the theme rewrite :)

**Comment by mattstratton** [comment]
This is actually turning out to be a lot easier than I thought, and I might have this fixed in a day or two.

**Comment by mattstratton** [comment]
So this has been accomplished! It's optional to break out the program stuff - take a look at the data files in `/data/events/2023/chicago` for an example!

**Comment by toshywoshy** [comment]
Thank you.
I will take a look at the example and work for AMS/GHENT/ANTWERP to test the new plugin for Pretalx
I have started some work on the Pretalx part, but it will still need some work
