### ISSUE TITLE
International date formatting?

### ISSUE THREAD

**Issue by phrawzty** [devopsdays/devopsdays-web#2038]
It would be really nice to support international date formatting for those that desire it.

Concretely, this would mean displaying automatically generated date strings as "DD mmmm" instead of the other way around. 😄  (October 2? No! 2 October. 😉 )

**Comment by mattstratton** [comment]
Can you open this in devopsdays/devopsdays-theme? :) We aren't tracking defects in this repo. I might actually need to turn issues off on this one to make that more clear.

Even better, since this is a feature request, can you pop it open in https://www.devopsdays.org/ideas so we can get it on the roadmap?

**Comment by phrawzty** [comment]
Oops, my bad! Will do!
