### ISSUE TITLE
Some events want the menu to link outside

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#76]
Again, see DC as an example. Should be able to override the destination of menu items such as "register"

**Comment by bridgetkromhout** [comment]
As a temporary measure, I'd imagine we could just have a placeholder local page that contains a redirect.

**Comment by mattstratton** [comment]
Totally. This isn't really that big of a deal to implement - we would probably end up just restructuring the `navigationelements` section of the data file to allow an optional additional value which would be a URL override.

**Comment by davidasnider** [comment]
This worked great for me, FYI.  However the change you reference wasn't reflected in the repository.  themes/devopsdays-legacy/layouts/event/single.html...  I had to update it to match what is in https://github.com/devopsdays/devopsdays-web/commit/5559e01c92fc0f47ed35f533b73695056ec0e310.  The problem is, now I'm afraid to commit it, because I don't 'own' that file.  Suggestions?

**Comment by mattstratton** [comment]
Oh I broke that. I'll fix it in a jiffy.
