### ISSUE TITLE
Update REFERENCE.md with some things that have changed

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#8169]
Stepping through https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-theme/REFERENCE.md, I can see that a few things are no longer relevant. These are the things that I am proposing to change (I want a second set of eyes on this to make sure I'm not removing something that is still used)

In `city-yyyy.yml`
- `coordinates` (this can be removed since we don't have the map display anymore; I don't think we use this anywhere else)
- `icon: "map-o"` under `nav_elements` (we don't display the icons on small screens anymore, so this isn't used, although I might want to keep it because I sorta want to add this in somewhere)
- `proposal_email` (I am pretty sure this is not used by the templates anymore, but there might be a shortcode that can leverage it?)

I also just noticed that there is now apparently a section in this file that lists shortcodes and how they work; it's incomplete and I should probably add the other ones to it.

**Comment by bridgetkromhout** [comment]
In general I think I’d rather have a deprecated column or put these in a deprecated section because people could be trying to learn from old event yaml files and find it confusing that there are undocumented keys. 

I think you’re right that an address, not coordinates, is used for the location page map. I don’t see much purpose to collecting coordinates. 

If we bring the icons (which I liked!) back, we also need accompanying text. Too confusing otherwise, alas. 

The templates don’t use special email options because I don’t plan to encourage that. They tend to be a lot of overhead and minimally used. But I think leaving it as a possibility people could customize with is okay?

**Comment by mattstratton** [comment]
I think what we can do for the proposal email field is make a short code like event_email that can be called from a page. Then it makes sense to keep it in case people want to use it. 

I agree about marking them as deprecated. I’ll ponder on the clearest way to do that.

**Comment by bridgetkromhout** [comment]
> I think what we can do for the proposal email field is make a short code like event_email that can be called from a page. Then it makes sense to keep it in case people want to use it.

This already exists: https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-theme/layouts/shortcodes/email_proposals.html. It can already be used. It's just not something I'm going to recommend by default by putting it into the recommended templates.

**Comment by mattstratton** [comment]
I realized that `coordinates` is used by `event_map`, so we don't want to remove that.

I agree that we probably don't want to remove the `icon` for now because we might want to use it sometime soon, and honestly, very few folks ever changed it, so it's not really that confusing to keep it in. I am just going to make a note about that in the file.

Basically, none of these things need updating, so I'm going to close this issue.
