### ISSUE TITLE
remove dependency on current and past parameters

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#882]
Based upon what we learned from creating the cfp page, we should be able to do queries based on the event dates properly now, so we can whack all `current`, etc, references.

**Comment by mattstratton** [comment]
This should resolve #247

**Comment by bridgetkromhout** [comment]
Unfortunately there are other places that use those parameters. One issue that comes up when I am not listing that parameter in a datafile any more is that there are future cities no longer listed on the map header, due to this line:

https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-responsive/layouts/partials/upcoming_headline.html#L4

**Comment by mattstratton** [comment]
Whoops :)

**Comment by bridgetkromhout** [comment]
I also spotted "current" in the map file: https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-responsive/layouts/partials/map.html#L25

**Comment by bridgetkromhout** [comment]
This is resolved in https://github.com/devopsdays/devopsdays-web/pull/1455.
